Add a job to build the PHAR

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -135,6 +135,47 @@ code_fixer: &code_fixer
       # run tests!
       - run: vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection -- src tests
 
+build_phar: &build_phar
+  steps:
+    - checkout
+
+    # Download and cache dependencies
+    - restore_cache:
+        keys:
+          - v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}-{{ checksum ".circleci/config.yml" }}
+          # fallback to using the latest cache if no exact match is found
+          - v2-test-dependencies-
+
+    # php:* has no zip extension and the CLI is faster to install.
+    - run: apt-get update -y && apt-get install unzip -y
+
+    - run: |
+        EXPECTED_SIGNATURE=$(curl -L https://composer.github.io/installer.sig)
+        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+        ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+
+        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+        then
+            >&2 echo 'ERROR: Invalid installer signature'
+            rm composer-setup.php
+            exit 1
+        fi
+
+        php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
+
+    - run: composer update -n --prefer-dist
+
+    - save_cache:
+        paths:
+          - /root/.composer/cache/files
+        key: v2-test-dependencies-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}-{{ checksum ".circleci/config.yml" }}
+
+    # Build the phar!
+    - run: composer build-phar
+
+    - store_artifacts:
+        path: ./har.phar
+
 jobs:
   build_php73:
     docker:
@@ -157,11 +198,19 @@ jobs:
 
   code_fixer:
     docker:
-      - image: php:7.2
+      - image: php:7.3
 
     working_directory: ~/repo
 
     <<: *code_fixer
+
+  build_phar:
+    docker:
+      - image: php:7.3
+
+    working_directory: ~/repo
+
+    <<: *build_phar
 
 workflows:
   version: 2
